name = "10k-hours"
pages_build_output_dir = "dist"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
BETTER_AUTH_URL = "https://10k-hours.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "10k-hours-db"
database_id = ""
preview_database_id = "DB"
